# Generated by Django 4.2.20 on 2025-05-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data_commento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='post_images/')),
                ('riconoscimento', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('latitudine', models.FloatField()),
                ('longitudine', models.FloatField()),
                ('data_pubblicazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
