# Generated by Django 4.2.20 on 2025-05-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
