# Generated by Django 4.2.20 on 2025-05-12 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domanda', models.TextField()),
                ('risposta_corretta', models.CharField(max_length=200)),
                ('difficolta', models.IntegerField(choices=[(1, 'Facile'), (2, 'Media'), (3, 'Difficile')])),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='badges.badge')),
            ],
        ),
    ]
