# Generated by Django 4.2.20 on 2025-05-22 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='difficolta',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='domanda',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='risposta_corretta',
        ),
        migrations.AddField(
            model_name='quiz',
            name='descrizione',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='titolo',
            field=models.CharField(default='Titolo quiz', max_length=200),
        ),
        migrations.CreateModel(
            name='RisultatoQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteggio', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Risposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(max_length=255)),
                ('corretta', models.BooleanField(default=False)),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risposte', to='quiz.domanda')),
            ],
        ),
        migrations.AddField(
            model_name='domanda',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domande', to='quiz.quiz'),
        ),
    ]
