# Generated by Django 4.2.20 on 2025-05-12 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('eco_rating', models.IntegerField()),
                ('materiali', models.TextField()),
                ('descrizione', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProdottoScansionato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_scansione', models.DateTimeField(auto_now_add=True)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodotti.prodotto')),
            ],
        ),
    ]
